### ISSUE TITLE
Add option to export database contents to sql

### ISSUE THREAD

**Issue by centic9** [fdev/phpmyadmin-cli#6]
phpMyAdmin provides a tab "export" which allows to export the full database contents and download the result as SQL file. 

It would be nice to be able to use this. It seems this tool already uses this tab for doing the queries, so it would probably be easy to do.

Use case is doing backups of a hosted website where the only interface to the database is phpMyAdmin and so an automated backup of the database needs to be done this way.

**Comment by fdev** [comment]
Thanks for the suggestion and the feature would indeed make sense. I'll try to find the time to include this feature as soon as possible.

**Comment by centic9** [comment]
In the meantime I already implemented it for me as I needed it, you can find it here: https://github.com/centic9/phpmyadmin-cli/commit/6aa9e2c50ee352da36b4f328b0d9a19f0165644f not sure if this approach is useful, but it allows me to backup the database periodically.

Let me know if the approach looks generally useful and I should do a PR from it.
